version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      ADDR: ":8080"
      DATABASE_URL: "postgres://chat:chat@db:5432/chat?sslmode=disable"
      JWT_SECRET: "dev-secret-change"
      ALLOWED_ORIGINS: "*"
      PURGE_INTERVAL_SECONDS: "300"
    ports:
      - "8080:8080"
    depends_on: [db]
volumes:
  pgdata: